# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='post',
            field=models.CharField(max_length=339),
        ),
    ]
