# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170417_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='visible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
